author:
  displayName: Jonathan Lurie
  biography: Hey 👋 I'm a scientific developer working on a brain atlas. I'm into 3D rendering for the web and graphics in general
  picture: https://github.com/jonathanlurie.png
  website: http://me.jonathanlurie.fr
  twitter: jonathanlurie
  github: jonathanlurie

# This section is not mandatory but it will show a list of articles in the profile page.
# Otherwise not article will be listed, though they will still be accessible through URL
articles:
  - getting-started
  - dummy-article
  - corrupted-article
  - some-code
