author:
  displayName: Jonathan Lurie
  biography: Hey 👋 I'm a scientific developer working on a brain atlas. I'm into 3D rendering for the web and graphics in general
  picture: https://github.com/jonathanlurie.png
  website: http://me.jonathanlurie.fr
  twitter: jonathanlurie
  github: jonathanlurie

articles:
  - scientific-developer
